apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  jwtPrivateKey: NTExMWQ4OWYtZGRlNQ==
  databaseDriver: bW9uZ29kYg==
  databaseHost: bW9uZ29kYitzcnY6Ly9jbHVzdGVyMC40bGVjMy5tb25nb2RiLm5ldA==
  packageDatabaseConnectionUrl: bW9uZ29kYitzcnY6Ly9ld2FuZ2NsYXJrczpKZXN1c2lzbG9yZGZvcmV2ZXJAY2x1c3RlcjAuNGxlYzMubW9uZ29kYi5uZXQvc3VwZXJhcHBfcGFja2FnZQ==
  deliveryDatabaseConnectionUrl: bW9uZ29kYitzcnY6Ly9ld2FuZ2NsYXJrczpKZXN1c2lzbG9yZGZvcmV2ZXJAY2x1c3RlcjAuNGxlYzMubW9uZ29kYi5uZXQvc3VwZXJhcHBfZGVsaXZlcnk=
  userDatabaseConnectionUrl: bW9uZ29kYitzcnY6Ly9ld2FuZ2NsYXJrczpKZXN1c2lzbG9yZGZvcmV2ZXJAY2x1c3RlcjAuNGxlYzMubW9uZ29kYi5uZXQvc3VwZXJhcHBfdXNlcg==
  databasePort: MjcwMTc=
  databaseUsername: ZXdhbmdjbGFya3M=
  packageServiceDatabaseName: c3VwZXJhcHBfcGFja2FnZQ==
  deliveryServiceDatabaseName: c3VwZXJhcHBfZGVsaXZlcnk=
  userServiceDatabaseName: c3VwZXJhcHBfdXNlcg==
  databasePassword: SmVzdXNpc2xvcmRmb3JldmVyNys=
  kafkaBrokers: cGtjLTEyNTc2ei51cy13ZXN0Mi5nY3AuY29uZmx1ZW50LmNsb3VkOjkwOTI=
  kafkaUsername: WkxPMk1OVUtYNjNNMzdXWA==
  kafkaPassword: cldzNVJ6Mm9KNFJiRDE2TVczZDFIY0huWWdWUGk0RHJKOE1VZVo5N0M4VTl3aXJYMUZHRG9mUzFpNER6Mk9SSg==
  kafkaGroupId: QUZSSUNBX1NVUEVSQVBQ
  gateWayHost: aHR0cDovL2FwaXNpeC1nYXRld2F5OjgwMDAsaHR0cDovL3dlYjo0MjAw
  jwtTokenExpiryTimeInHours: Mmg=
  elasticCloudId: YWZyaWNhc3VwZXJhcHA6ZFhNdFkyVnVkSEpoYkRFdVoyTndMbU5zYjNWa0xtVnpMbWx2SkRKaU5XTXpOVEJrTnprelpUUXdOVE01WXpNeFlqQTVPVEZqT1RJNVpEVmhKR1JoWlRnNE9EWmpNamM0WkRReFpXVmlaR05pTlRBeE9XUm1OMlV3T1daaw==
  elasticUsername: ZWxhc3RpYw==
  elasticPassword: cFBFanM4eVc3aVRqUUlJWExqUW5HQmZr
  bcryptSalt: MTA=
  googleApiKey: QUl6YVN5Q2JicUJVVkdkZnhaN29rSWQ0QlZNX0R5YzJqZVBueVJr
