apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 1
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: 590183838260.dkr.ecr.us-east-1.amazonaws.com/africasuperapp-user-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8003
          env:
            - name: jwt_private_key
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwtPrivateKey
            - name: db_driver
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: databaseDriver
            - name: db_host
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: databaseHost
            - name: db_port
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: databasePort
            - name: db_username
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: databaseUsername
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key:  databasePassword
            - name: db_name
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: userServiceDatabaseName
            - name: db_connectionUrl
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key:  userDatabaseConnectionUrl
            - name: kafka_brokers
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: kafkaBrokers
            - name: gateway_host
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: gateWayHost
            - name: expiry_time
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwtTokenExpiryTimeInHours
            - name:  elastic_cloud_id
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: elasticCloudId
            - name: elasticUsername
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: elasticUsername
            - name: elastic_password
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: elasticPassword
            - name: bcrypt_salt
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: bcryptSalt
            - name: elastic_logs_index
              valueFrom:
                configMapKeyRef:
                  name: app-config-map
                  key: elasticLogsIndex
            - name: elastic_logging_level
              valueFrom:
                configMapKeyRef:
                  name: app-config-map
                  key: logLevel
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config-map
                  key: nodeEnv
      imagePullSecrets:
        - name: registry-credentials
      restartPolicy: Always
  selector:
    matchLabels:
      app: user-service

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: "TCP"
      port: 8003
      targetPort: http
  type: ClusterIP